"""added created_At field

Revision ID: fab9d1ff4c1a
Revises: 2be76473cfe8
Create Date: 2026-03-06 02:03:36.230156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fab9d1ff4c1a'
down_revision: Union[str, Sequence[str], None] = '2be76473cfe8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('created_At', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'created_At')
    # ### end Alembic commands ###
